src/components/layout/ImageLayer/ImageLayer.tsx, src/hooks/useImageLayer.ts, src/pages/CreateQuiz/composite/QuizWriteForm/QuestionForm.tsx, src/pages/SolveQuiz/index.tsx
=> Feat(DK-543): 퀴즈 작성 시 해설 이미지 클릭 확대 적용

src/pages/CreateQuiz/composite/CreateQuizComplete/CreateQuizComplete.tsx
- fromInternal: 퀴즈 접속 경로(내부/외부)를 파악하는 상태
=> Fix(DK-547): 퀴즈 생성 후 퀴즈 풀러가기 버튼 클릭 시 fromInternal state 추가 (누락되었던)

src/pages/QuizResult/composite/StudyQuizResult.tsx, src/pages/QuizResult/index.tsx, src/pages/QuizReview/index.tsx
=> Fix(DK-539): 스터디 퀴즈 풀기 후 스터디 상세 페이지로 리다이렉트

public/assets/svg/common/correct.svg, public/assets/svg/common/incorrect.svg, src/pages/MyPage/composite/accountSetting/EditMyInfo/EditMyInfo.tsx, src/pages/MyPage/composite/accountSetting/EditMyInfo/_edit_my_info.module.scss
- 에러메시지를 input의 message 파라미터 사용하도록 변경
=> Fix(DK-534): 마이페이지 - 닉네임, 이메일 변경시 레이아웃 잘못된 부분 수정

src/pages/QuizResult/composite/StudyQuizResult.tsx, src/pages/QuizResult/index.tsx, src/pages/QuizReview/index.tsx
=> Release 1.2.1 Fix(DK-539): 스터디 퀴즈 풀기 후 스터디 페이지로 리다이렉트

src/components/atom/Checkbox/Checkbox.tsx, src/components/atom/RadioOption/RadioOption.tsx, src/pages/SolveQuiz/composite/SolvingQuizForm.tsx, src/pages/SolveQuiz/composite/_solving_quiz_form.module.scss
- 퀴즈 제목, 퀴즈 옵션, 퀴즈 해설에서 마크다운 지원하도록 구현
=> Release 1.2.1 Fix(DK-532): 마크다운 보이도록 수정

src/pages/CreateQuiz/layout/QuizCreationFormLayout/QuizCreationFormLayout.tsx
- 기존에는 퀴즈 Id가 지정되지 않아 url이 잘못되어있었음
- 퀴즈 작성완료시 id 지정해줘서 해결
=> Release 1.2.1  Fix(DK-557): 퀴즈 수정하기 완료 화면에서 퀴즈 풀러가기 url 수정

src/pages/CreateQuiz/index.tsx, src/pages/SolveQuiz/index.tsx
- 모달 버튼 2개인 경우 primary-border(왼), primary(오)
=> Style(DK-541): 모달 버튼 색상 수정

src/pages/CreateQuiz/index.tsx, src/pages/SolveQuiz/index.tsx
- 모달 버튼 2개인 경우 primary-border(왼), primary(오)
=> release 1.2.2 Style(DK-541): 모달 버튼 색상 수정

src/components/atom/Checkbox/Checkbox.tsx, src/components/atom/Checkbox/_checkbox.module.scss, src/components/atom/RadioOption/RadioOption.tsx, src/components/atom/RadioOption/_radio_option.module.scss
- 옵션이 길어지면 라디오, 체크박스 컴포넌트를 vertical-start정렬
- 퀴즈 옵션 선택된 상태에서도 focus상태이면 x버튼 색 gray 60으로 지정
=> Release 1.2.2 Fix(DK-560): 퀴즈 옵션 디자인 변경 반영

src/pages/Register/composite/TermsAgreement/TermsAgreement.tsx, src/validation/passwordValidation.ts
- 선택 약관 해제 시 '모두 동의' 해제되도록 로직 수정
- 회원가입 비밀번호 대문자와 소문자가 모두 포함되도록 비밀번호 검증 규칙 수정 (+ 영문 -> 대소문자로 워딩 변경)
=> Fix(DK-578): 회원가입 페이지 수정사항 반영

src/pages/MyPage/components/QuizItem/_quiz_item.module.scss
=> Style(DK-579): 마이페이지 퀴즈 아이템 스타일 수정

src/data/queryKeys.ts, src/hooks/mutate/useDeleteQuiz.ts, src/pages/BookDetail/index.tsx, src/pages/CreateQuiz/index.tsx, src/pages/CreateQuiz/layout/QuizCreationFormLayout/QuizCreationFormLayout.tsx, src/pages/MyPage/layout/QuizListLayout/QuizListLayout.tsx, src/pages/QuizDetail/index.tsx, src/pages/QuizResult/composite/CommonQuizResult.tsx, src/pages/QuizResult/composite/StudyQuizResult.tsx, src/pages/QuizResult/index.tsx, src/pages/SolveQuiz/index.tsx, src/services/server/bookService.ts, src/services/server/quizService.ts, src/services/server/reviewService.ts
- servce파일, querykey파일에 쓰이는 id값의 type을 컨벤션대로 number로 통일하였습니다.
=> Refactor(DK-476): service파일과 queryKey파일안에 쓰이는 id값의 type을 number로 통일

index.html, package.json, vite.config.ts
=> Refactor(DK-582): 성능개선

yarn.lock
=> Chore(DK-582): 성능개선 누락된파일 추가

src/App.tsx, src/route/router.tsx
- routes의 파일들을 모두 lazy loading으로 구현
=> Refactor(DK-582): 성능개선을 위한 lazy loading방식 구현

vite.config.ts, yarn.lock
- react, reactRouter, animation관련으로 나눠 설정
=> Refactor(DK-582): 성능개선을 위해 manualChunks설정

src/data/queryKeys.ts, src/hooks/mutate/useDeleteQuiz.ts, src/pages/BookDetail/index.tsx, src/pages/CreateQuiz/index.tsx, src/pages/CreateQuiz/layout/QuizCreationFormLayout/QuizCreationFormLayout.tsx, src/pages/MyPage/layout/QuizListLayout/QuizListLayout.tsx, src/pages/QuizDetail/index.tsx, src/pages/QuizResult/composite/CommonQuizResult.tsx, src/pages/QuizResult/composite/StudyQuizResult.tsx, src/pages/QuizResult/index.tsx, src/pages/SolveQuiz/index.tsx, src/services/server/bookService.ts, src/services/server/quizService.ts, src/services/server/reviewService.ts
- api 요청시 number type으로 요청하기 때문에 number로 통일
=> Release 1.2.4 Refactor(DK-476): service파일과 queryKey파일안에 쓰이는 id값의 type을 number로 통일

index.html, package.json, src/App.tsx, src/route/router.tsx, vite.config.ts, yarn.lock
- 텍스트 압축 패키지 적용
- 불필요한 cdn제거
- 성능개선을 위한 lazy loading방식 구현
- 성능개선을 위해 manualChunks설정
=> Release 1.2.4 Refactor(DK-582): lighthouse FCP개선

src/styles/base/_base.scss, src/styles/base/_fonts.scss, src/styles/base/_index.scss, src/styles/base/_reset.scss, src/styles/main.scss
=> Release 1.2.6 Fix(DK-584): 폰트 적용 안되는 문제 수정

src/pages/MyPage/components/ProfileImageEditor/ProfileImageEditor.tsx, src/pages/MyPage/composite/MyStudyGroupsCreate/MyStudyGroupsCreate.tsx, src/pages/MyPage/composite/StudyGroupSetting/StudyGroupSetting.tsx, src/pages/MyPage/composite/StudyGroupSetting/_study_group_setting.module.scss
- 프로필 이미지 삭제 버튼 disabled 속성 추가
- 폰트 사진 수정
=> Release 1.2.6 Style(DK-585): 스터디 그룹 관리 스타일링 변경 적용

src/pages/MyPage/composite/StudyGroupSetting/StudyGroupSetting.tsx
- 누락되어있던 기능 픽스했습니다.
- 혜림님 찾아주셔서 감사합니다!
=> Release 1.2.6 Fix(DK-585): 스터디 그룹 관리 사진 삭제 시에도 변경사항 버튼 뜨도록 수정

src/pages/BookList/layout/BookListLayout/BookListLayout.tsx, src/pages/MyPage/composite/accountSetting/EditMyInfo/EditMyInfo.tsx
- 가다나순 오타 수정
- 닉네임 공백삽입 제거 및 변경방지
=> Release 1.3 Fix(DK-590): 사용성테스트시 발견된 오류 수정

src/pages/CreateQuiz/composite/QuizWriteForm/CheckBoxQuestionTemplate.tsx, src/pages/CreateQuiz/composite/QuizWriteForm/OXQuestionTemplate.tsx, src/pages/CreateQuiz/index.tsx
- ox,복수정답 생성 시 question이 없을 경우 에러 발생 문제 수정
- 첫 생성 퀴즈 임시저장 시 (이어쓰기가 아닌) 같은 퀴즈가 다른 아이디로 저장되는 문제 (여러개 생성됨) 수정
- `isEditMode` 상태를 올바르게 추적하도록 state에서 ref로 변경
=> Release 1.3.1 Fix(DK-603): 퀴즈 임시저장 오류 수정
